# ==========================================
# Log4j2 Configuration
# Console + Rolling File (INFO only)
# ==========================================

# Config Name
name=PropertiesConfig

# Folder for logs
property.filename = logs

# Appenders used
appenders = console, rolling

# ------------------------------------------
# Console Appender
# ------------------------------------------
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# ------------------------------------------
# Rolling File Appender
# ------------------------------------------

appender.rolling.type = RollingFile
appender.rolling.name = LOGFILE
appender.rolling.fileName = ${filename}/mylog.log
appender.rolling.filePattern = ${filename}/mylog-%d{yyyy-MMMM-dd_HH.mm.ss}.log
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.rolling.filter.threshold.type = ThresholdFilter
appender.rolling.filter.threshold.level = INFO
appender.rolling.filter.threshold.onMatch = ACCEPT
appender.rolling.filter.threshold.onMismatch = DENY

appender.rolling.policies.type = Policies
appender.rolling.policies.startup.type = OnStartupTriggeringPolicy

# ------------------------------------------
# Root Logger
# ------------------------------------------
rootLogger.level = debug
rootLogger.appenderRefs = console, rolling
rootLogger.appenderRef.console.ref = STDOUT
rootLogger.appenderRef.rolling.ref = LOGFILE


<Logger name="com.yourpackage" level="debug" additivity="false">
    <AppenderRef ref="Console"/>
   # <AppenderRef ref="File"/>
</Logger>